
package com.genee.event;

public enum EventType {

  APP_STARTED, TALKING,
  LISTEN_WAKEUP_WORD, LISTENING_WAKEUP_WORD, WAKE_UP, STOP_LISTEN_WAKEUP_WORD, 
  LISTEN_SPEECH_WORD, LISTENING_SPEECH_WORD, RECEIVED_SPEECH_WORD, STOP_LISTEN_SPEECH_WORD,
  LISTEN_SPEECH, LISTENING_SPEECH, PROCESS_SPEECH, STOP_LISTEN_SPEECH

}
